package com.optionslab.engine.risk

import java.math.BigDecimal
import java.math.RoundingMode

/**
 * The shared risk core, ported from IraAlgo's `services/risk/`.
 *
 * One place decides whether a position has hit its stop, taken its target,
 * earned a tighter trailing stop, or whether a set of positions has run past
 * its combined limits. The rule that makes it shareable is the same one the
 * Python states: **no I/O of any kind** - no clock, no feed, no broker, no
 * storage. Every input arrives as an argument and every decision leaves as a
 * return value, so the phone and the platform judge a tick identically.
 *
 * The port is literal on purpose, down to Python's comparison order in
 * `max()`/`min()` and its float formatting, because the parity fixtures in
 * `src/test/resources/risk/` are generated by running the Python and the
 * decisions are compared field for field, detail text included.
 */

/**
 * The favourable excursion a position must show before a trail may move its
 * stop. 1.0 is IraAlgo's shipped MIN_TRAIL_PROFIT, kept so adopting the core
 * does not silently re-tune anybody's live stops.
 */
const val DEFAULT_TRAIL_TRIGGER = 1.0

/** Position direction, in IraAlgo's order constants. */
enum class Side(val wire: String) {
    BUY("BUY"), SELL("SELL");

    override fun toString() = wire
}

/**
 * How a trailing stop derives its new level. CONTINUOUS keeps a fixed gap
 * behind the best price actually seen; STEPPED advances the configured initial
 * stop one step per completed trigger of favourable movement.
 */
enum class TrailMode(val wire: String) {
    CONTINUOUS("continuous"), STEPPED("stepped");

    override fun toString() = wire
}

/**
 * Why a rule fired. The per-position values `sl` / `target` are the wire
 * contract the scalping service and browser already speak; the aggregate
 * values follow the strategy PRD's `exit_detail` vocabulary.
 */
enum class BreachReason(val wire: String) {
    STOP("sl"),
    TARGET("target"),
    COMBINED_STOP("combined_sl"),
    COMBINED_TARGET("combined_target"),
    LOCK_PROFIT("lock_profit");

    override fun toString() = wire

    companion object {
        fun fromWire(s: String?): BreachReason? = entries.firstOrNull { it.wire == s }
    }
}

/**
 * Input normalisation with Python's semantics.
 *
 * The Python core accepts untrusted, loosely typed values (a DB row, a wire
 * payload, a REST body), so "is this a price" has to answer the same way for
 * a string, a bool, a NaN or a missing key on both sides. These helpers are
 * what lets [PositionRisk.fromState] take a `Map<String, Any?>` and agree with
 * `PositionRisk.from_state` on every alias and every junk value.
 */
object RiskValues {
    private val PY_FLOAT = Regex("""[+-]?(?:(?:\d(?:_?\d)*)(?:\.(?:\d(?:_?\d)*)?)?|\.\d(?:_?\d)*)(?:[eE][+-]?\d(?:_?\d)*)?""")
    private val PY_SPECIAL = Regex("""[+-]?(?:inf|infinity|nan)""", RegexOption.IGNORE_CASE)

    /**
     * Python's `float(value)`, or null where Python raises. Bools are the
     * caller's concern: every Python call site excludes them before converting.
     */
    fun pyFloat(value: Any?): Double? = when (value) {
        null -> null
        is Boolean -> if (value) 1.0 else 0.0
        is Number -> value.toDouble()
        is String -> {
            val t = value.trim()
            when {
                PY_SPECIAL.matches(t) -> {
                    val neg = t.startsWith("-")
                    if (t.trimStart('+', '-').lowercase() == "nan") Double.NaN
                    else if (neg) Double.NEGATIVE_INFINITY else Double.POSITIVE_INFINITY
                }
                PY_FLOAT.matches(t) -> t.replace("_", "").toDouble()
                else -> null
            }
        }
        else -> null
    }

    /**
     * True when `value` is a usable, strictly positive, finite price.
     *
     * Zero is deliberately not a price: nothing on an Indian exchange trades at
     * or below zero, so a zero stop is a missing value that arrived as a
     * numeric default, and reading it literally makes a short with
     * `current_sl = 0` breach on every tick.
     */
    fun isPrice(value: Any?): Boolean {
        if (value == null || value is Boolean) return false
        val n = pyFloat(value) ?: return false
        return n.isFinite() && n > 0.0
    }

    /** Coerce to a finite double, falling back to [default] for anything unusable. */
    fun asFloat(value: Any?, default: Double = 0.0): Double {
        if (value == null || value is Boolean) return default
        val n = pyFloat(value) ?: return default
        return if (n.isFinite()) n else default
    }

    /** Coerce to a price, or null when the value is not a usable price. */
    fun asPrice(value: Any?): Double? = if (isPrice(value)) pyFloat(value) else null

    /** Like [asFloat] but null, not a default, for anything unusable. */
    fun optionalFloat(value: Any?): Double? {
        if (value == null || value is Boolean) return null
        val n = pyFloat(value) ?: return null
        return if (n.isFinite()) n else null
    }

    /** Python truthiness, for the `bool(x)` / `x or y` reads in `from_state`. */
    fun truthy(value: Any?): Boolean = when (value) {
        null -> false
        is Boolean -> value
        is Double -> value != 0.0 || value.isNaN()
        is Float -> value != 0.0f || value.isNaN()
        is Number -> value.toLong() != 0L
        is String -> value.isNotEmpty()
        is Collection<*> -> value.isNotEmpty()
        is Map<*, *> -> value.isNotEmpty()
        else -> true
    }

    /** Python's `str(value)` for the scalar types a loose state can carry. */
    fun pyStr(value: Any?): String = when (value) {
        null -> "None"
        is Boolean -> if (value) "True" else "False"
        is Double -> pyRepr(value)
        is Float -> pyRepr(value.toDouble())
        else -> value.toString()
    }

    /** Python's `repr(float)`: `5.0`, `1e-05`, `1e+16`, `inf`, `nan`. */
    fun pyRepr(d: Double): String {
        if (d.isNaN()) return "nan"
        if (d.isInfinite()) return if (d > 0) "inf" else "-inf"
        if (d == 0.0) return if (1.0 / d < 0) "-0.0" else "0.0"
        val bd = BigDecimal(d.toString()).stripTrailingZeros()
        val exp = bd.precision() - bd.scale() - 1
        if (exp < -4 || exp >= 16) {
            val digits = bd.unscaledValue().abs().toString()
            val mant = if (digits.length == 1) digits else digits[0] + "." + digits.substring(1)
            val sign = if (d < 0) "-" else ""
            val es = if (exp < 0) "-" else "+"
            return sign + mant + "e" + es + String.format("%02d", kotlin.math.abs(exp))
        }
        val plain = bd.toPlainString()
        return if (plain.contains('.')) plain else "$plain.0"
    }

    /** Python's `max(a, b)`: `a` unless `b` compares strictly greater. NaN-order faithful. */
    fun pyMax(a: Double, b: Double): Double = if (b > a) b else a

    /** Python's `min(a, b)`: `a` unless `b` compares strictly smaller. */
    fun pyMin(a: Double, b: Double): Double = if (b < a) b else a

    /**
     * Map anything a caller might send to a [Side]. Unknown values fall back to
     * BUY, as the shipped scalping engine does; `validatePosition` is where a
     * genuinely lost side should be caught, not an exception on the tick path.
     */
    fun normaliseSide(value: Any?): Side {
        if (value is Side) return value
        val text = (if (truthy(value)) pyStr(value) else "").trim().uppercase()
        return if (text in setOf("SELL", "S", "SHORT", "-1")) Side.SELL else Side.BUY
    }

    fun normaliseTrailMode(value: Any?): TrailMode {
        if (value is TrailMode) return value
        val text = (if (truthy(value)) pyStr(value) else "").trim().lowercase()
        return if (text in setOf("stepped", "step", "staircase")) TrailMode.STEPPED else TrailMode.CONTINUOUS
    }

    /** A points-based stop distance as the absolute stop price, or null. */
    fun stopFromPoints(side: Any?, entryPrice: Any?, points: Any?): Double? {
        if (!isPrice(entryPrice) || !isPrice(points)) return null
        val entry = pyFloat(entryPrice)!!
        val distance = pyFloat(points)!!
        val price = if (normaliseSide(side) == Side.BUY) entry - distance else entry + distance
        return if (price > 0.0) price else null
    }

    /** A points-based target distance as the absolute target price, or null. */
    fun targetFromPoints(side: Any?, entryPrice: Any?, points: Any?): Double? {
        if (!isPrice(entryPrice) || !isPrice(points)) return null
        val entry = pyFloat(entryPrice)!!
        val distance = pyFloat(points)!!
        val price = if (normaliseSide(side) == Side.BUY) entry + distance else entry - distance
        return if (price > 0.0) price else null
    }

    /** The side of a signed net quantity, as a position book reports it. */
    fun sideFromQuantity(netQuantity: Any?): Side = if (asFloat(netQuantity) < 0.0) Side.SELL else Side.BUY

    /**
     * Compact plain-text price for a detail line: Python's
     * `f"{v:.4f}".rstrip("0").rstrip(".")`.
     *
     * Rounded from the exact binary value, half to even, as Python does.
     * `String.format` rounds the shortest decimal half-up instead, and the two
     * disagree on values like 1.00005, which would make a detail string drift.
     */
    fun formatPrice(value: Double): String {
        val text = fixed(value, 4).trimEnd('0').trimEnd('.')
        return text.ifEmpty { "0" }
    }

    /** Python's `f"{v:.Nf}"`, exact-binary half-even, signed zero kept. */
    fun fixed(value: Double, places: Int): String {
        if (value.isNaN()) return "nan"
        if (value.isInfinite()) return if (value > 0) "inf" else "-inf"
        var s = BigDecimal(value).setScale(places, RoundingMode.HALF_EVEN).toPlainString()
        if (!s.startsWith("-") && (value < 0.0 || 1.0 / value < 0.0)) s = "-$s"
        return s
    }
}
