package com.optionslab.engine.strategy

import com.optionslab.engine.risk.Side
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.LocalTime
import java.time.ZonedDateTime
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * SCENARIO TESTS, derived from reading the Python rather than generated by
 * running it. The decisions inside each step (resolution, risk, fills,
 * claims, gates) are parity-tested in [StrategyParityTest]; what these cover
 * is the orchestration upstream performs with a database, a broker and a
 * scheduler in the loop - start/ack/fill/tick/stop sequencing, working-entry
 * cancels, refused-exit retry, signal flips and session roll, scheduler
 * polling and persistence - none of which is callable in isolation there.
 */
class RuntimeScenarioTest {
    private val rt = StrategyRuntime()

    /** Monday 4 May 2026, 10:00 IST. */
    private val monday = ZonedDateTime.of(2026, 5, 4, 10, 0, 0, 0, IST)
    private fun at(h: Int, m: Int, day: LocalDate = monday.toLocalDate()) = ZonedDateTime.of(day, LocalTime.of(h, m), IST)

    private val contract = MasterContract(
        buildList {
            for (e in listOf("05-MAY-26", "12-MAY-26", "26-MAY-26")) {
                val sym = e.replace("-", "")
                for (i in 0..8) {
                    val s = 23400.0 + 50 * i
                    add(Instrument("NIFTY$sym${s.toInt()}CE", "NFO", "NIFTY", e, s, 65, "CE"))
                    add(Instrument("NIFTY$sym${s.toInt()}PE", "NFO", "NIFTY", e, s, 65, "PE"))
                }
            }
            add(Instrument("NIFTY26MAY26FUT", "NFO", "NIFTY", "26-MAY-26", null, 65, "FUTIDX"))
            add(Instrument("RELIANCE", "NSE", "RELIANCE", null, null, 1, "EQ"))
        },
    )

    private fun straddle(
        overallSl: Double? = null, trailToEntry: Boolean = false, exitTime: LocalTime? = LocalTime.of(15, 15),
        dailyLoss: Double? = null, product: Product = Product.NRML,
    ) = StrategyDef(
        id = 3, name = "Straddle", underlying = "NIFTY", underlyingExchange = "NSE_INDEX",
        entryTime = LocalTime.of(9, 20), exitTime = exitTime, product = product,
        legs = listOf(
            LegDef(1, Segment.OPTIONS, Position.S, 1, OptionType.CE, StrikeMode.ATM, "ATM", expiry = "weekly", slPts = 10.0),
            LegDef(2, Segment.OPTIONS, Position.S, 1, OptionType.PE, StrikeMode.ATM, "ATM", expiry = "weekly", slPts = 10.0),
            LegDef(3, Segment.OPTIONS, Position.B, 1, OptionType.CE, StrikeMode.ATM, "OTM2", expiry = "weekly"),
        ),
        overallSlMtm = overallSl, trailSlToEntry = trailToEntry, dailyLossLimitInr = dailyLoss,
    )

    private fun orders(actions: List<Action>) = actions.filterIsInstance<Action.PlaceOrder>()
    private fun events(actions: List<Action>) = actions.mapNotNull { (it as? Action.Log)?.event ?: (it as? Action.Alert)?.event }

    /** Start, ack every entry, fill every entry at [price]. */
    private fun filledRun(def: StrategyDef, price: Double = 100.0): RunState {
        val (started, actions) = rt.start(def, SymbolResolver.resolve(def, contract, 23590.0, monday), monday, 11)
        var run = started
        for (o in orders(actions)) {
            run = rt.onOrderAck(run, def, o.orderId, true, now = monday).first
            run = rt.onOrderUpdate(run, def, OrderUpdate(o.orderId, "complete", o.quantity, price), monday).first
        }
        return run
    }

    private fun fillAll(run0: RunState, def: StrategyDef, actions: List<Action>, price: Double): Pair<RunState, List<Action>> {
        var run = run0
        val out = ArrayList<Action>()
        for (o in orders(actions)) {
            val (a, x) = rt.onOrderAck(run, def, o.orderId, true, now = monday)
            val (b, y) = rt.onOrderUpdate(a, def, OrderUpdate(o.orderId, "traded", o.quantity, price), monday)
            run = b
            out += x + y
        }
        return run to out
    }

    @Test fun `every leg of a basket resolves around one ATM and BUY legs are placed before SELL legs`() {
        val def = straddle()
        val resolved = SymbolResolver.resolve(def, contract, 23590.0, monday)
        assertTrue(resolved.all { it.ok }, resolved.toString())
        assertEquals(listOf("NIFTY05MAY2623600CE", "NIFTY05MAY2623600PE", "NIFTY05MAY2623700CE"), resolved.map { it.symbol })
        assertEquals(setOf(23600.0), resolved.map { it.atmStrike }.toSet())

        val (run, actions) = rt.start(def, resolved, monday, 11)
        assertTrue(actions.first() is Action.Subscribe, "prices are asked for before the entries go out")
        val placed = orders(actions)
        assertEquals(listOf(3, 1, 2), placed.map { it.legId }, "the long wing goes first")
        assertEquals(listOf(Side.BUY, Side.SELL, Side.SELL), placed.map { it.side })
        assertEquals(setOf("NRML"), placed.map { it.product }.toSet())
        assertEquals(setOf(65), placed.map { it.quantity }.toSet())
        assertEquals(RunStatus.ENTERING, run.status)
        assertEquals("run_started", events(actions).first().kind)
    }

    @Test fun `a start is refused whole when any leg cannot be resolved, and a signal strategy has no start`() {
        val def = straddle().copy(legs = straddle().legs + LegDef(4, Segment.OPTIONS, Position.B, 1, OptionType.PE, StrikeMode.ATM, "OTM5", expiry = "weekly"))
        val (run, actions) = rt.start(def, SymbolResolver.resolve(def, contract, 23590.0, monday), monday, 11)
        assertEquals(RunStatus.IDLE, run.status)
        assertTrue(run.startError!!.startsWith("Leg 4: Offset OTM5 runs off the end"), run.startError)
        assertTrue(orders(actions).isEmpty())

        val signal = straddle().copy(kind = StrategyKind.SIGNAL)
        assertTrue(rt.start(signal, emptyList(), monday, 12).first.startError!!.startsWith("A signal strategy has no start"))
        assertEquals(
            "This strategy is not enabled for live trading. Enable it first.",
            rt.start(straddle(), SymbolResolver.resolve(straddle(), contract, 23590.0, monday), monday, 13, RunMode.LIVE).first.startError,
        )
    }

    @Test fun `every entry refused finalises the run as error with the venue's own words`() {
        val def = straddle()
        var (run, actions) = rt.start(def, SymbolResolver.resolve(def, contract, 23590.0, monday), monday, 11)
        val all = ArrayList<Action>()
        for (o in orders(actions)) run = rt.onOrderAck(run, def, o.orderId, false, "Insufficient funds", monday).also { all += it.second }.first
        assertEquals(RunStatus.CLOSED, run.status)
        assertEquals("error", run.stopReason)
        assertEquals("Every entry order was rejected: Insufficient funds", events(all).last { it.kind == "start_failed" }.message)
    }

    @Test fun `a leg stop exits that leg once, at market, on the opposite side, and the run closes when flat`() {
        val def = straddle()
        var run = filledRun(def)
        assertEquals(RunStatus.ACTIVE, run.status)
        val ce = run.leg(1)!!
        val (r1, a1) = rt.onTick(run, def, listOf(Quote(ce.symbol, "NFO", 111.0)), monday)
        val exits = orders(a1)
        assertEquals(1, exits.size)
        assertEquals("exit_sl", exits[0].kind)
        assertEquals(Side.BUY, exits[0].side, "a short is covered by a BUY, never sold again")
        assertEquals("MARKET", exits[0].priceType)
        assertTrue(events(a1).any { it.kind == "leg_sl_hit" })

        val (r2, a2) = rt.onTick(r1, def, listOf(Quote(ce.symbol, "NFO", 112.0)), monday)
        assertTrue(orders(a2).isEmpty(), "an exit already in flight is not sent twice")

        run = fillAll(r2, def, a1, 111.0).first
        assertEquals("closed", run.leg(1)!!.status)
        assertEquals(-11.0 * 65, run.leg(1)!!.realizedPnl, 1e-9)
        assertEquals(RunStatus.ACTIVE, run.status)

        val (r3, a3) = rt.closeLeg(run, def, 2, monday)
        assertEquals("exit_leg_manual", orders(a3).single().kind)
        val (r4, a4) = rt.closeLeg(fillAll(r3, def, a3, 100.0).first, def, 3, monday)
        val (done, closing) = fillAll(r4, def, a4, 100.0)
        assertEquals(RunStatus.CLOSED, done.status)
        assertEquals("manual", done.stopReason)
        assertTrue(events(closing).any { it.kind == "run_stopped" && it.message == "All legs closed" })
        assertTrue(closing.any { it is Action.Unsubscribe })
    }

    @Test fun `a stop moves the other legs to entry when asked, and a manual close never does`() {
        val def = straddle(trailToEntry = true)
        val run = filledRun(def)
        // The CE short stops out; the PE short, in profit, is made risk free.
        val (r1, a1) = rt.onTick(run, def, listOf(Quote(run.leg(2)!!.symbol, "NFO", 90.0), Quote(run.leg(1)!!.symbol, "NFO", 111.0)), monday)
        assertTrue(events(a1).any { it.kind == "trail_to_entry_activated" })
        assertEquals(100.0, r1.leg(2)!!.effectiveSl)
        assertTrue(r1.trailToEntryActive)

        val (r2, _) = rt.closeLeg(filledRun(def), def, 1, monday)
        assertNull(r2.leg(2)!!.effectiveSl, "a manual close leaves the other stops alone")
        assertFalse(r2.trailToEntryActive)
    }

    @Test fun `a combined stop closes the whole basket and finalises with its reason once flat`() {
        val def = straddle(overallSl = 500.0)
        val run = filledRun(def)
        val (r1, a1) = rt.onTick(run, def, listOf(Quote(run.leg(1)!!.symbol, "NFO", 108.0)), monday)
        assertEquals(RunStatus.EXITING, r1.status)
        assertEquals("overall_sl", r1.stopRequestedReason)
        assertEquals(listOf("exit_overall_sl"), orders(a1).map { it.kind }.distinct())
        assertEquals(3, orders(a1).size)
        val (done, a2) = fillAll(r1, def, a1, 108.0)
        assertEquals(RunStatus.CLOSED, done.status)
        assertEquals("overall_sl", done.stopReason)
        assertTrue(events(a2).any { it.message == "Run stopped (overall_sl)" })
    }

    @Test fun `an intraday run squares off at its exit time and the daily loss limit counts the session`() {
        val def = straddle()
        val (r1, a1) = rt.onTick(filledRun(def), def, emptyList(), at(15, 15))
        assertEquals("scheduler", r1.stopRequestedReason)
        assertEquals(setOf("exit_close_all"), orders(a1).map { it.kind }.toSet())

        val limited = straddle(dailyLoss = 1000.0)
        val run = filledRun(limited)
        val (r2, a2) = rt.onTick(run, limited, listOf(Quote(run.leg(1)!!.symbol, "NFO", 103.0)), monday, bankedSessionPnl = -900.0)
        assertEquals("daily_loss_limit", r2.stopRequestedReason)
        assertEquals("Daily loss limit reached: the session is down 1095.00 against a limit of 1000.00", events(a2).first { it.kind == "overall_sl_hit" }.message)
        assertEquals(setOf("exit_daily_loss_limit"), orders(a2).map { it.kind }.toSet())

        val earlier = RunState(1, 3, startedAt = at(9, 30), pnlRealized = -400.0)
        val yesterday = RunState(2, 3, startedAt = at(14, 0, monday.toLocalDate().minusDays(1)), pnlRealized = -5000.0)
        assertEquals(-400.0, StrategyRuntime.sessionBankedPnl(listOf(earlier, yesterday), 3, 11, monday))
    }

    @Test fun `a stop cancels a working entry instead of reversing it, and finishes when the cancel lands`() {
        val def = straddle()
        var (run, actions) = rt.start(def, SymbolResolver.resolve(def, contract, 23590.0, monday), monday, 11)
        val placed = orders(actions)
        for (o in placed) run = rt.onOrderAck(run, def, o.orderId, true, now = monday).first
        // Two entries fill, one is still working when the operator stops.
        for (o in placed.take(2)) run = rt.onOrderUpdate(run, def, OrderUpdate(o.orderId, "complete", o.quantity, 100.0), monday).first
        val working = placed[2]
        val (r1, a1) = rt.closeAll(run, def, monday)
        assertEquals(listOf(Action.CancelOrder(working.orderId, working.legId)), a1.filterIsInstance<Action.CancelOrder>())
        assertEquals(2, orders(a1).size, "only confirmed quantities are exited")
        assertFalse(events(a1).any { it.kind == "run_stop_failed" }, "a pending cancel is not a refused stop")
        val (r2, _) = fillAll(r1, def, a1, 100.0)
        assertEquals(RunStatus.EXITING, r2.status, "the working entry keeps the run managed")
        val (done, _) = rt.onOrderUpdate(r2, def, OrderUpdate(working.orderId, "cancelled", 0), monday)
        assertEquals(RunStatus.CLOSED, done.status)
        assertEquals("manual", done.stopReason)
    }

    @Test fun `an entry that fills after the stop is exited at its filled size at once`() {
        val def = straddle()
        var (run, actions) = rt.start(def, SymbolResolver.resolve(def, contract, 23590.0, monday), monday, 11)
        val placed = orders(actions)
        for (o in placed) run = rt.onOrderAck(run, def, o.orderId, true, now = monday).first
        val (r1, _) = rt.closeAll(run, def, monday)
        val (r2, a2) = rt.onOrderUpdate(r1, def, OrderUpdate(placed[0].orderId, "open", 30, 100.0), monday)
        assertTrue(orders(a2).isEmpty(), "a partial, still-working entry is not squared off")
        val (_, a3) = rt.onOrderUpdate(r2, def, OrderUpdate(placed[0].orderId, "complete", 40, 100.0), monday)
        assertEquals(40, orders(a3).single().quantity)
        assertEquals("exit_close_all", orders(a3).single().kind)
    }

    @Test fun `a refused exit releases its claim, says so at critical, and the pending stop retries it`() {
        val def = straddle()
        val (r1, a1) = rt.closeAll(filledRun(def), def, monday)
        val refused = orders(a1).first()
        val (r2, a2) = rt.onOrderAck(r1, def, refused.orderId, false, "RMS: rate limited", monday)
        assertTrue(a2.filterIsInstance<Action.Alert>().any { it.event.kind == "leg_exit_rejected" })
        assertNull(r2.leg(refused.legId)!!.exitKind)
        val (_, a3) = rt.reconcilePendingStop(r2, def, monday)
        assertEquals(listOf(refused.legId), orders(a3).map { it.legId })
    }

    @Test fun `broker frames fold cumulatively and an exit is priced by its new quantity only`() {
        val def = straddle()
        val run = filledRun(def)
        val (r1, a1) = rt.closeLeg(run, def, 3, monday)
        val exit = orders(a1).single()
        var r = rt.onOrderAck(r1, def, exit.orderId, true, now = monday).first
        r = rt.onOrderUpdate(r, def, OrderUpdate(exit.orderId, "open", 20, 110.0), monday).first
        assertEquals(45, r.leg(3)!!.qty)
        r = rt.onOrderUpdate(r, def, OrderUpdate(exit.orderId, "open", 20, 110.0), monday).first
        assertEquals(45, r.leg(3)!!.qty, "a repeated frame adds nothing")
        r = rt.onOrderUpdate(r, def, OrderUpdate(exit.orderId, "complete", 65, 116.0), monday).first
        // 20 @ 110, then 45 whose price is (116*65 - 110*20) / 45 = 118.666...
        assertEquals(10.0 * 20 + (116.0 * 65 - 110.0 * 20 - 100.0 * 45), r.leg(3)!!.realizedPnl, 1e-6)
        assertEquals("closed", r.leg(3)!!.status)
    }

    @Test fun `runtime calls never mutate the state they are given`() {
        val def = straddle()
        val run = filledRun(def)
        val before = RunStateCodec.encode(run)
        rt.onTick(run, def, listOf(Quote(run.leg(1)!!.symbol, "NFO", 130.0)), monday)
        rt.closeAll(run, def, monday)
        assertEquals(before, RunStateCodec.encode(run))
    }

    // ---------------------------------------------------------------- signals

    private val signalDef = StrategyDef(
        id = 9, name = "Alerts", kind = StrategyKind.SIGNAL, underlying = "RELIANCE", underlyingExchange = "NSE",
        entryTime = LocalTime.of(9, 15), exitTime = LocalTime.of(15, 20), product = Product.MIS,
        legs = listOf(LegDef(1, Segment.CASH, symbol = "RELIANCE", exchange = "NSE", side = LegSide.BOTH, qty = 10, qtyMode = QtyMode.UNITS, slPts = 5.0)),
    )

    private fun settle(out: SignalOutcome, price: Double): RunState {
        var run = out.run!!
        for (o in orders(out.actions)) {
            run = rt.onOrderAck(run, signalDef, o.orderId, true, now = monday).first
            run = rt.onOrderUpdate(run, signalDef, OrderUpdate(o.orderId, "complete", o.quantity, price), monday).first
        }
        return run
    }

    @Test fun `a signal opens the session's run, repeats are no-ops, and a flip squares then reverses`() {
        val first = rt.onSignal(null, signalDef, "long_entry", contract, monday, newRunId = 21, legId = 1)
        assertTrue(first.result.acted)
        assertEquals(RunMode.SANDBOX, first.run!!.mode, "live is opt-in")
        assertEquals(Side.BUY, orders(first.actions).single().side)
        assertEquals("MIS", orders(first.actions).single().product)
        var run = settle(first, 2500.0)

        val again = rt.onSignal(run, signalDef, "long_entry", contract, monday, 22, legId = 1)
        assertEquals("already_long", again.result.note)
        assertTrue(again.result.ok)
        assertTrue(orders(again.actions).isEmpty())

        val flip = rt.onSignal(run, signalDef, "short_entry", contract, monday, 22, legId = 1)
        assertTrue(flip.result.flipped)
        assertEquals(listOf("exit_signal" to Side.SELL, "entry" to Side.SELL), orders(flip.actions).map { it.kind to it.side })
        assertNotNull(flip.run!!.leg(1)!!.superseded, "the outgoing long is kept until its exit fills")
        run = settle(flip, 2510.0)
        assertNull(run.leg(1)!!.superseded)
        assertEquals("S", run.leg(1)!!.position)
        assertEquals(100.0, run.leg(1)!!.realizedPnl, 1e-9, "the long's round trip is booked on the leg")

        assertEquals("no_matching_position", rt.onSignal(run, signalDef, "long_exit", contract, monday, 22, legId = 1).result.note)
        val out = rt.onSignal(run, signalDef, "short_exit", contract, monday, 22, legId = 1)
        run = settle(out, 2490.0)
        assertEquals(RunStatus.ACTIVE, run.status, "a signal run stays open for the session when flat")
        assertEquals(300.0, run.pnlRealized, 1e-9)
    }

    @Test fun `signal windows, the carry-short refusal and the session roll`() {
        assertEquals("outside_trading_window", rt.onSignal(null, signalDef, "long_exit", contract, at(15, 25), 21, legId = 1).result.note)
        assertEquals("outside_entry_window", rt.onSignal(null, signalDef, "long_entry", contract, at(9, 0), 21, legId = 1).result.note)

        val carry = signalDef.copy(product = Product.CNC)
        val refused = rt.onSignal(null, carry, "short_entry", contract, monday, 21, legId = 1)
        assertFalse(refused.result.ok)
        assertTrue(refused.result.error!!.startsWith("Leg 1: cash cannot be held short overnight"))
        assertTrue(orders(refused.actions).isEmpty())

        // Yesterday's run still holds a long: the first signal today rolls it through an eod stop.
        val y = settle(rt.onSignal(null, signalDef, "long_entry", contract, monday.minusDays(1), 21, legId = 1), 2500.0)
        val today = rt.onSignal(y, signalDef, "long_entry", contract, monday, 22, legId = 1)
        assertEquals("run_stopping", today.result.note, "no entry while the stale run is still being closed")
        assertEquals("eod", today.run!!.stopRequestedReason)
        assertEquals(listOf("exit_eod"), orders(today.actions).map { it.kind })

        // Once flat, the stale run is finalised and a fresh one opens.
        val flatStale = settle(rt.onSignal(y, signalDef, "long_exit", contract, monday.minusDays(1).withHour(11), 21, legId = 1), 2505.0)
        val rolled = rt.onSignal(flatStale, signalDef, "long_entry", contract, monday, 22, legId = 1)
        assertEquals("eod", rolled.rolledRun!!.stopReason)
        assertEquals(22, rolled.run!!.runId)
        assertTrue(rolled.result.acted)
    }

    // -------------------------------------------------------------- scheduler

    @Test fun `scheduler jobs fire in IST within the misfire grace, coalesce, and honour a holiday hook for starts only`() {
        val def = straddle().copy(
            scheduler = SchedulerConfig(true, DayOfWeek.entries.take(5), LocalTime.of(9, 20), LocalTime.of(15, 10), RunMode.SANDBOX),
        )
        assertEquals(listOf("strategy:3:start", "strategy:3:stop"), Scheduler.plannedJobs(def).map { it.jobId })
        assertEquals(listOf(Scheduler.JobKind.START), Scheduler.due(def, at(9, 19, ), at(9, 20).plusSeconds(30)).map { it.job.kind })
        assertTrue(Scheduler.due(def, at(9, 20).plusSeconds(30), at(9, 21)).isEmpty(), "each slot fires once")
        assertTrue(Scheduler.due(def, at(9, 0), at(9, 25)).isEmpty(), "a slot missed by more than a minute is dropped")
        val holiday: (LocalDate) -> Boolean = { it == monday.toLocalDate() }
        assertTrue(Scheduler.due(def, at(9, 19), at(9, 20), holiday).isEmpty())
        assertEquals(listOf(Scheduler.JobKind.STOP), Scheduler.due(def, at(15, 9), at(15, 10), holiday).map { it.job.kind })
        val friday = at(16, 0, monday.toLocalDate().plusDays(4))
        assertEquals(at(9, 20, monday.toLocalDate().plusDays(7)), Scheduler.nextFire(Scheduler.plannedJobs(def)[0], friday))
        // The device clock's zone does not matter: 03:50 UTC is 09:20 IST.
        assertEquals(1, Scheduler.due(def, null, at(9, 20).withZoneSameInstant(java.time.ZoneOffset.UTC)).size)

        // With the scheduler off, exit_time still squares off, on weekdays.
        val off = straddle()
        assertEquals("Strategy 3 scheduled square-off (exit_time)", Scheduler.plannedJobs(off).single().name)
        assertEquals(1, Scheduler.due(off, null, at(15, 15)).size)
        assertTrue(Scheduler.due(off, null, at(15, 15, monday.toLocalDate().plusDays(5))).isEmpty())

        assertEquals(Scheduler.StartDecision.Start(RunMode.SANDBOX), Scheduler.startDecision(def, running = false))
        assertEquals(Scheduler.StartDecision.Skip("already running"), Scheduler.startDecision(def, running = true))
        val live = def.copy(scheduler = def.scheduler!!.copy(defaultMode = RunMode.LIVE))
        assertTrue(Scheduler.startDecision(live, false) is Scheduler.StartDecision.Refuse)
        assertEquals("scheduler", Scheduler.stopDecision(running = true))
    }

    // ------------------------------------------------------------ persistence

    @Test fun `strategy and run state round-trip through JSON`() {
        val def = straddle(overallSl = 5000.0, trailToEntry = true, dailyLoss = 7500.0).copy(
            lockProfit = LockProfit(LockProfitMode.LOCK_AND_TRAIL, 3000.0, 1000.0, 250.0, lockProfitWhole = true),
            scheduler = SchedulerConfig(true, listOf(DayOfWeek.MONDAY, DayOfWeek.THURSDAY), LocalTime.of(9, 20), LocalTime.of(15, 5), RunMode.LIVE),
            webhookIpAllowlist = listOf("10.0.0.0/8"), liveEnabled = true,
        )
        assertEquals(def, StrategyCodec.decode(StrategyCodec.encode(def)))
        assertEquals(signalDef, StrategyCodec.decode(StrategyCodec.encode(signalDef)))

        val (run, actions) = rt.closeAll(filledRun(def), def, monday)
        assertTrue(orders(actions).isNotEmpty())
        val json = RunStateCodec.encode(run)
        assertEquals(json, RunStateCodec.encode(RunStateCodec.decode(json)))

        // A checkpoint leg written by the Python loads as-is.
        val leg = RunStateCodec.legFromMap(
            Json.parse(
                """{"leg_id": 2, "position": "S", "symbol": "NIFTY05MAY2623600PE", "exchange": "NFO", "lots": 1, "qty": 65,
                "position_ref": "9f2c", "entry_order_id": 41, "entry_status": "complete", "entry_filled_qty": 0, "entry_avg": 101.5,
                "exit_order_id": null, "exit_claim_token": null, "exit_kind": null, "exit_avg": null, "ltp": 99.0, "mtm": 162.5,
                "realized_pnl": 0.0, "status": "open", "tick_source": "ws", "risk_unit": "points", "sl_pts": 10, "target_pts": null,
                "trail_x": 0, "trail_y": 0, "effective_sl": 111.5, "effective_target": null, "trail_active": false,
                "highest_price": null, "lowest_price": 98.25, "superseded": null}""",
            ) as Map<String, Any?>,
        )
        assertEquals(111.5, leg.effectiveSl)
        assertEquals(10.0, leg.slPts)
        assertEquals(41L, leg.entryOrderId)
    }
}
